name: moodtune
description: "A daily journal app with personalized daily music recommendations."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  either_dart: ^1.0.0
  dio: ^5.8.0+1
  logger: ^2.6.0
  envied: ^1.1.1
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  lucide_icons: ^0.257.0
  flutter_quill: ^11.4.1
  sqflite: ^2.4.2
  path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1 
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  freezed: ^3.1.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/

flutter_icons:
  android: true      
  ios: true
  image_path: "assets/images/moodtune.png"
  remove_alpha_ios: true   

